searchMicroserviceName: search-microservice
searchMicroserviceReplicas: 1
searchMicroserviceImage: chuchulev/search-microservice:latest
searchMicroserviceInitialDelaySeconds: 90
searchMicroserviceLivenessProbePath: /health/live
searchMicroserviceLivenessProbePort: 8001
searchMicroserviceLivenessProbePeriodSeconds: 10
searchMicroserviceLivenessProbeTimeoutSeconds: 1
searchMicroserviceLivenessProbeFailureThreshold: 3
searchMicroserviceReadinessProbePath: /health/ready
searchMicroserviceReadinessProbePort: 8001
searchMicroserviceReadinessProbeInitialDelaySeconds: 10
searchMicroserviceReadinessProbePeriodSeconds: 10
searchMicroserviceReadinessProbeTimeoutSeconds: 1
searchMicroserviceReadinessProbeFailureThreshold: 3
searchMicroserviceHttpPort: 8000
searchMicroserviceMetricsPort: 8001
searchMicroserviceHealthPort: 8000
searchMicroservicePeriodSeconds: 5
searchMicroserviceTerminationGracePeriodSeconds: 30

searchMicroserviceLogging:
  level: info
  devMode: false
  encoder: json

resources:
  requests:
    memory: "256Mi"
    cpu: "300m"
  limits:
    memory: "1000Mi"
    cpu: "1000m"

# Jaeger collector HTTP endpoint (jaeger-client-go ReporterConfig)
jaegerHostPort: "http://jaeger:14268/api/traces"
rabbitMqURI: amqp://guest:guest@rabbitmq:5672/
elasticSearchURL: http://elastic:9200

http:
  development: true
  basePath: /api/v1
  productsPath: /api/v1/products
  debugErrorsResponse: true
  ignoreLogUrls: [ "metrics", "swagger" ]

prometheusPath: /metrics

elasticIndexes:
  products:
    path: config/mappings.json
    name: products
    alias: products-alias

exchangeAndQueueBindings:
  indexProductBinding:
    exchangeName: products
    exchangeKind: direct
    queueName: index-product
    bindingKey: products-index
    concurrency: 10
    consumer: products-consumer

bulkIndexer:
  numWorkers: 10
  flushBytes: 20000000
  flushIntervalSeconds: 15
  timeoutMilliseconds: 5000