// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: email.proto

package userService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Email message
type Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailId       string                 `protobuf:"bytes,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	To            []string               `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	ContentType   string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{0}
}

func (x *Email) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *Email) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Email) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Email) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Email) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Email) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Email) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// SendEmailRequest is the request for the SendEmail method
type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            []string               `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// SendEmailResponse is the response for the SendEmail method
type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_email_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{2}
}

func (x *SendEmailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Find email by id request
type FindEmailByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailUuid     string                 `protobuf:"bytes,1,opt,name=email_uuid,json=emailUuid,proto3" json:"email_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEmailByIdRequest) Reset() {
	*x = FindEmailByIdRequest{}
	mi := &file_email_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEmailByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEmailByIdRequest) ProtoMessage() {}

func (x *FindEmailByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEmailByIdRequest.ProtoReflect.Descriptor instead.
func (*FindEmailByIdRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{3}
}

func (x *FindEmailByIdRequest) GetEmailUuid() string {
	if x != nil {
		return x.EmailUuid
	}
	return ""
}

// Find email by id response
type FindEmailByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *Email                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEmailByIdResponse) Reset() {
	*x = FindEmailByIdResponse{}
	mi := &file_email_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEmailByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEmailByIdResponse) ProtoMessage() {}

func (x *FindEmailByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEmailByIdResponse.ProtoReflect.Descriptor instead.
func (*FindEmailByIdResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{4}
}

func (x *FindEmailByIdResponse) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

// Find emails by receiver request
type FindEmailsByReceiverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverEmail string                 `protobuf:"bytes,1,opt,name=receiver_email,json=receiverEmail,proto3" json:"receiver_email,omitempty"`
	Page          uint64                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEmailsByReceiverRequest) Reset() {
	*x = FindEmailsByReceiverRequest{}
	mi := &file_email_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEmailsByReceiverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEmailsByReceiverRequest) ProtoMessage() {}

func (x *FindEmailsByReceiverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEmailsByReceiverRequest.ProtoReflect.Descriptor instead.
func (*FindEmailsByReceiverRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{5}
}

func (x *FindEmailsByReceiverRequest) GetReceiverEmail() string {
	if x != nil {
		return x.ReceiverEmail
	}
	return ""
}

func (x *FindEmailsByReceiverRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindEmailsByReceiverRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Find emails by receiver response
type FindEmailsByReceiverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         []*Email               `protobuf:"bytes,1,rep,name=email,proto3" json:"email,omitempty"`
	TotalPages    uint64                 `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Page          uint64                 `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint64                 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEmailsByReceiverResponse) Reset() {
	*x = FindEmailsByReceiverResponse{}
	mi := &file_email_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEmailsByReceiverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEmailsByReceiverResponse) ProtoMessage() {}

func (x *FindEmailsByReceiverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEmailsByReceiverResponse.ProtoReflect.Descriptor instead.
func (*FindEmailsByReceiverResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{6}
}

func (x *FindEmailsByReceiverResponse) GetEmail() []*Email {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *FindEmailsByReceiverResponse) GetTotalPages() uint64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *FindEmailsByReceiverResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *FindEmailsByReceiverResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *FindEmailsByReceiverResponse) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindEmailsByReceiverResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_email_proto protoreflect.FileDescriptor

const file_email_proto_rawDesc = "" +
	"\n" +
	"\vemail.proto\x12\vuserService\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd2\x01\n" +
	"\x05Email\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\tR\aemailId\x12\x0e\n" +
	"\x02to\x18\x02 \x03(\tR\x02to\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"P\n" +
	"\x10SendEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x03(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"+\n" +
	"\x11SendEmailResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"5\n" +
	"\x14FindEmailByIdRequest\x12\x1d\n" +
	"\n" +
	"email_uuid\x18\x01 \x01(\tR\temailUuid\"A\n" +
	"\x15FindEmailByIdResponse\x12(\n" +
	"\x05email\x18\x01 \x01(\v2\x12.userService.EmailR\x05email\"l\n" +
	"\x1bFindEmailsByReceiverRequest\x12%\n" +
	"\x0ereceiver_email\x18\x01 \x01(\tR\rreceiverEmail\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x04R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"\xcd\x01\n" +
	"\x1cFindEmailsByReceiverResponse\x12(\n" +
	"\x05email\x18\x01 \x03(\v2\x12.userService.EmailR\x05email\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x04R\n" +
	"totalPages\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x04R\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x04R\x04page\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x04R\x04size2\x9f\x02\n" +
	"\fEmailService\x12J\n" +
	"\tSendEmail\x12\x1d.userService.SendEmailRequest\x1a\x1e.userService.SendEmailResponse\x12V\n" +
	"\rFindEmailById\x12!.userService.FindEmailByIdRequest\x1a\".userService.FindEmailByIdResponse\x12k\n" +
	"\x14FindEmailsByReceiver\x12(.userService.FindEmailsByReceiverRequest\x1a).userService.FindEmailsByReceiverResponseB\x0fZ\r.;userServiceb\x06proto3"

var (
	file_email_proto_rawDescOnce sync.Once
	file_email_proto_rawDescData []byte
)

func file_email_proto_rawDescGZIP() []byte {
	file_email_proto_rawDescOnce.Do(func() {
		file_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_email_proto_rawDesc), len(file_email_proto_rawDesc)))
	})
	return file_email_proto_rawDescData
}

var file_email_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_email_proto_goTypes = []any{
	(*Email)(nil),                        // 0: userService.Email
	(*SendEmailRequest)(nil),             // 1: userService.SendEmailRequest
	(*SendEmailResponse)(nil),            // 2: userService.SendEmailResponse
	(*FindEmailByIdRequest)(nil),         // 3: userService.FindEmailByIdRequest
	(*FindEmailByIdResponse)(nil),        // 4: userService.FindEmailByIdResponse
	(*FindEmailsByReceiverRequest)(nil),  // 5: userService.FindEmailsByReceiverRequest
	(*FindEmailsByReceiverResponse)(nil), // 6: userService.FindEmailsByReceiverResponse
	(*timestamppb.Timestamp)(nil),        // 7: google.protobuf.Timestamp
}
var file_email_proto_depIdxs = []int32{
	7, // 0: userService.Email.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: userService.FindEmailByIdResponse.email:type_name -> userService.Email
	0, // 2: userService.FindEmailsByReceiverResponse.email:type_name -> userService.Email
	1, // 3: userService.EmailService.SendEmail:input_type -> userService.SendEmailRequest
	3, // 4: userService.EmailService.FindEmailById:input_type -> userService.FindEmailByIdRequest
	5, // 5: userService.EmailService.FindEmailsByReceiver:input_type -> userService.FindEmailsByReceiverRequest
	2, // 6: userService.EmailService.SendEmail:output_type -> userService.SendEmailResponse
	4, // 7: userService.EmailService.FindEmailById:output_type -> userService.FindEmailByIdResponse
	6, // 8: userService.EmailService.FindEmailsByReceiver:output_type -> userService.FindEmailsByReceiverResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_email_proto_init() }
func file_email_proto_init() {
	if File_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_email_proto_rawDesc), len(file_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_email_proto_goTypes,
		DependencyIndexes: file_email_proto_depIdxs,
		MessageInfos:      file_email_proto_msgTypes,
	}.Build()
	File_email_proto = out.File
	file_email_proto_goTypes = nil
	file_email_proto_depIdxs = nil
}
